from django.db import models

# Create your models here.
class Medicamentos(models.Model):
    MedicamentoRegistro = models.CharField(primary_key=True, db_column='registro')
    MedicamentoPrincipioAtivo = models.TextField(db_column='principio_ativo')
    MedicamentoCnpj = models.CharField(max_length=18, db_column='cnpj')
    MedicamentoLaboratorio = models.CharField(max_length=150, db_column='laboratorio')
    MedicamentoCodGgrem = models.BigIntegerField(db_column='codigo_ggrem')
    MedicamentoEan1 = models.CharField(max_length=50, db_column='ean_1')
    MedicamentoEan2 = models.CharField(max_length=50, db_column='ean_2')
    MedicamentoEan3 = models.CharField(max_length=50, db_column='ean_3')
    MedicamentoProduto = models.CharField(max_length=100, db_column='produto')
    MedicamentoApresentacao = models.CharField(max_length=150, db_column='apresentacao')
    MedicamentoClasseTerapeutica = models.CharField(max_length=100, db_column='classe_terapeutica')
    MedicamentoTipoProduto = models.CharField(max_length=50, db_column='tipo_produto_status_produto')
    MedicamentoRegimePreco = models.CharField(max_length=30, db_column='regime_preco')
    MedicamentoPfSemImposto = models.FloatField(db_column='pf_sem_impostos')
    MedicamentoPf0 = models.FloatField(db_column='pf_0')
    MedicamentoPf12 = models.FloatField(db_column='pf_12')
    MedicamentoPf17 = models.FloatField(db_column='pf_17')
    MedicamentoPf17Alc = models.FloatField(db_column='pf_17_alc')
    MedicamentoPf17Meio = models.FloatField(db_column='pf_17_5')
    MedicamentoPf17MeioAlc = models.FloatField(db_column='pf_17_5_alc')
    MedicamentoPf18 = models.FloatField(db_column='pf_18')
    MedicamentoPf18Alc = models.FloatField(db_column='pf_18_alc')
    MedicamentoPf19 = models.FloatField(db_column='pf_19')
    MedicamentoPf20 = models.FloatField(db_column='pf_20')
    MedicamentoPf21 = models.FloatField(db_column='pf_21')
    MedicamentoPf22 = models.FloatField(db_column='pf_22')
    MedicamentoPmvgSemImposto = models.FloatField(db_column='pmvg_sem_impostos')
    MedicamentoPmvg0 = models.FloatField(db_column='pmvg_0')
    MedicamentoPmvg12 = models.FloatField(db_column='pmvg_12')
    MedicamentoPfPmvg17 = models.FloatField(db_column='pmvg_17')
    MedicamentoPmvg17Alc = models.FloatField(db_column='pmvg_17_alc')
    MedicamentoPmvg17Meio = models.FloatField(db_column='pmvg_17_5')
    MedicamentoPmvg17MeioAlc = models.FloatField(db_column='pmvg_17_5_alc')
    MedicamentoPmvg18 = models.FloatField(db_column='pmvg_18')
    MedicamentoPmvg18Alc = models.FloatField(db_column='pmvg_18_alc')
    MedicamentoPmvg19 = models.FloatField(db_column='pmvg_19')
    MedicamentoPmvg20 = models.FloatField(db_column='pmvg_20')
    MedicamentoPmvg21 = models.FloatField(db_column='pmvg_21')
    MedicamentoPmvg22 = models.FloatField(db_column='pmvg_22')
    MedicamentoRestricaoHospitalar = models.CharField(max_length=3, db_column='restricao_hospitalar')
    MedicamentoCap = models.CharField(max_length=3, db_column='cap')
    MedicamentoComfaz87 = models.CharField(max_length=3, db_column='confaz_87')
    MedicamentoIcms0 = models.CharField(max_length=3, db_column='icms_0')
    MedicamentoAnaliseRecursal = models.CharField(max_length=30, db_column='analise_recursal')
    MedicamentoPisConfins = models.CharField(max_length=30, db_column='pis_cofins')
    MedicamentoComercializacao2022 = models.CharField(max_length=3, db_column='comercializacao_2022')
    MedicamentoTarja = models.CharField(max_length=30, db_column='tarja')
    