# Generated by Django 4.2.3 on 2023-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('MedicamentoRegistro', models.CharField(db_column='registro', primary_key=True, serialize=False)),
                ('MedicamentoPrincipioAtivo', models.CharField(db_column='principio_ativo', max_length=100)),
                ('MedicamentoCnpj', models.CharField(db_column='cnpj', max_length=18)),
                ('MedicamentoLaboratorio', models.CharField(db_column='laboratorio', max_length=150)),
                ('MedicamentoCodGgrem', models.IntegerField(db_column='codigo_ggrem')),
                ('MedicamentoEan1', models.CharField(db_column='ean_1', max_length=50)),
                ('MedicamentoEan2', models.CharField(db_column='ean_2', max_length=50)),
                ('MedicamentoEan3', models.CharField(db_column='ean_3', max_length=50)),
                ('MedicamentoProduto', models.CharField(db_column='produto', max_length=100)),
                ('MedicamentoApresentacao', models.CharField(db_column='apresentacao', max_length=150)),
                ('MedicamentoClasseTerapeutica', models.CharField(db_column='classe_terapeutica', max_length=100)),
                ('MedicamentoTipoProduto', models.CharField(db_column='tipo_produto_status_produto', max_length=50)),
                ('MedicamentoRegimePreco', models.CharField(db_column='regime_preco', max_length=30)),
                ('MedicamentoPfSemImposto', models.FloatField(db_column='pf_sem_impostos')),
                ('MedicamentoPf0', models.FloatField(db_column='pf_0')),
                ('MedicamentoPf12', models.FloatField(db_column='pf_12')),
                ('MedicamentoPf17', models.FloatField(db_column='pf_17')),
                ('MedicamentoPf17Alc', models.FloatField(db_column='pf_17_alc')),
                ('MedicamentoPf17Meio', models.FloatField(db_column='pf_17_5')),
                ('MedicamentoPf17MeioAlc', models.FloatField(db_column='pf_17_5_alc')),
                ('MedicamentoPf18', models.FloatField(db_column='pf_18')),
                ('MedicamentoPf18Alc', models.FloatField(db_column='pf_18_alc')),
                ('MedicamentoPf19', models.FloatField(db_column='pf_19')),
                ('MedicamentoPf20', models.FloatField(db_column='pf_20')),
                ('MedicamentoPf21', models.FloatField(db_column='pf_21')),
                ('MedicamentoPf22', models.FloatField(db_column='pf_22')),
                ('MedicamentoPmvgSemImposto', models.FloatField(db_column='pmvg_sem_impostos')),
                ('MedicamentoPmvg0', models.FloatField(db_column='pmvg_0')),
                ('MedicamentoPmvg12', models.FloatField(db_column='pmvg_12')),
                ('MedicamentoPfPmvg17', models.FloatField(db_column='pmvg_17')),
                ('MedicamentoPmvg17Alc', models.FloatField(db_column='pmvg_17_alc')),
                ('MedicamentoPmvg17Meio', models.FloatField(db_column='pmvg_17_5')),
                ('MedicamentoPmvg17MeioAlc', models.FloatField(db_column='pmvg_17_5_alc')),
                ('MedicamentoPmvg18', models.FloatField(db_column='pmvg_18')),
                ('MedicamentoPmvg18Alc', models.FloatField(db_column='pmvg_18_alc')),
                ('MedicamentoPmvg19', models.FloatField(db_column='pmvg_19')),
                ('MedicamentoPmvg20', models.FloatField(db_column='pmvg_20')),
                ('MedicamentoPmvg21', models.FloatField(db_column='pmvg_21')),
                ('MedicamentoPmvg22', models.FloatField(db_column='pmvg_22')),
                ('MedicamentoRestricaoHospitalar', models.CharField(db_column='restricao_hospitalar', max_length=3)),
                ('MedicamentoCap', models.CharField(db_column='cap', max_length=3)),
                ('MedicamentoComfaz87', models.CharField(db_column='confaz_87', max_length=3)),
                ('MedicamentoIcms0', models.CharField(db_column='icms_0', max_length=3)),
                ('MedicamentoAnaliseRecursal', models.CharField(db_column='analise_recursal', max_length=30)),
                ('MedicamentoPisConfins', models.CharField(db_column='pis_cofins', max_length=30)),
                ('MedicamentoComercializacao2022', models.CharField(db_column='comercializacao_2022', max_length=3)),
                ('MedicamentoTarja', models.CharField(db_column='tarja', max_length=30)),
            ],
        ),
    ]
