# Generated by Django 4.2.3 on 2023-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='MedicamentoCodGgrem',
            field=models.BigIntegerField(db_column='codigo_ggrem'),
        ),
    ]
